routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');//->middleware('sess');
Route::resource('staff',\App\Http\Controllers\StaffController::class);
Route::resource('staff.userList',\App\Http\Controllers\StaffUserListController::class);
Route::resource('staff.doctorList',\App\Http\Controllers\StaffDoctorListController::class);
Route::get('userList/{userList}/delete/{id}',[App\Http\Controllers\StaffUserListController::class,'delete'])->name('userList.delete');
Route::resource('staff.forum',\App\Http\Controllers\StaffForumController::class);
Route::resource('staff.forum.comment',\App\Http\Controllers\StaffCommentController::class);
Route::resource('staff.feedback',\App\Http\Controllers\StaffFeedbackController::class);
Route::put('/staff/{staff}/doctorList/{doctorList}/ban/{id}',[App\Http\Controllers\StaffDoctorListController::class,'ban'])->name('doctorList.ban');

app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    use HasFactory;
    protected $primaryKey='s_id';
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StaffRequests;
use App\Models\admin;
use App\Models\Staff;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

//use Illuminate\Support\Facades\Auth;
//use Illuminate\Support\Facades\DB;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    /*$doctor=DB::table('staff')
            ->rightJoin('users','staff.s_id','=','users.id')
            ->where('userId','=',Auth::user()->id)
            ->get();
    print_r($staff);
    return view('staff.profile')->with('users',$users);*/
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {   $staff=DB::table('staff')
        ->join('users','staff.userId','=','users.id')
        ->where('userId','=',Auth::user()->id)
        ->get();
        //print_r($doctor);
        if(count($staff)) {

            return view('staff.index')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
        return view('staff.index')->with('user',$staff[0]);

    }
    /*public function profile(Request $request)
    {
        $staff=DB::table('staff')
            ->join('users','staff.userId','=','users.id')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)) {

            return view('staff.index')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
        return view('staff.profile')->with('user',$staff[0]);
    }*/
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)==0){
            $request->session()->flash('msg','Please Complete Your Profile');
            return view('staff.create');
        }
        else{
            return redirect()->route('staff.index');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StaffRequests $request)
    {
        $staff=new Staff();
        $staff->phone=$request->phone;
        $staff->gender=$request->gender;
        $staff->userId=Auth::user()->id;

        if($request->hasFile('photo')){
            $file=$request->file('photo');
        //  echo "File Name: ". $file->getClientOriginalName()."<br>";
        //  echo "File Extension: ". $file->getClientOriginalExtension()."<br>";
        //   echo "File Size: ". $file->getSize()."<br>";
        //  echo "File Mime Type: ". $file->getMimeType();
            $filename=$file->getClientOriginalName();

            if($file->move('img', $filename)){
                $staff->photo = $filename;
                $staff->save();
                return redirect()->route('staff.index');
            }
            else{
                return redirect()->route('staff.create');
            }
        }
        else{
            echo 'Profile photo is not selected';
        }

    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,Staff $staff)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)) {

            return view('staff.index')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$staff)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)) {
            $staff=DB::table('staff')
                ->where('userId','=',Auth::user()->id)
                ->get();
            return view('staff.edit')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function update(StaffUpdateRequests $request, $staff)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        $staff->phone=$request->phone;
        $staff->gender=$request->gender;

        if($request->hasFile('photo')){
            $file=$request->file('photo');
//            echo "File Name: ". $file->getClientOriginalName()."<br>";
//            echo "File Extension: ". $file->getClientOriginalExtension()."<br>";
//            echo "File Size: ". $file->getSize()."<br>";
//            echo "File Mime Type: ". $file->getMimeType();
            $filename=$file->getClientOriginalName();

            if($file->move('img', $filename)){
                $staff->photo=$filename;

            }

        }
        $staff->save();
        return redirect()->route('staff.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function destroy(Staff $staff)
    {
        //
    }
}

resources/views/staff/create.blade.php
@extends('layouts.staff')

@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <div class="text-center">
                            <div class="h5 text-danger">
                                {{session('msg')}}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{route('staff.store')}}" enctype="multipart/form-data">
                            @csrf

                            <div class="row">
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="phone"><strong>Phone:</strong></label>
                                        <input type="text" class="form-control" name="phone"
                                               id="phone" placeholder="Phone" value="{{old('phone')}}"/>
                                    </div>
                                </div>

                                <div class="col-12 col-md-3">
                                    <div class="form-group">
                                        <label for="gender"><strong>Gender:</strong></label>
                                        <select class="form-control" name="gender" id="gender">
                                            <option selected>Male</option>
                                            <option>Female</option>
                                            <option>Other</option>
                                        </select>
                                    </div>
                                </div>

                            <div class="form-group">
                                <label for="photo"><strong>Profile Picture:</strong></label>
                                <input type="file" class="form-control-file" name="photo" id="photo" accept="image/*">
                            </div>

                            <div class="row">
                                 <div class=" col-12 text-center">
                                    <input type="submit" class="btn btn-primary pr-3 pl-3" value="Submit" id="submit"/>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>

            </div>
            <div class="col-auto">
            </div>
        </div>
        <div class="row">
            <div class="col-12 offset-sm-2 col-sm-8 text-danger">
                @foreach($errors->all() as $err)
                    {{$err}} <br>
                @endforeach
            </div>
        </div>
    </div>

@endsection

resources/views/staff/edit.blade.php
@extends('layouts.staff')

@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <div class="text-center">
                            <div class="h5">
                                Edit Profile
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{route('staff.update',Auth::User()->id)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                            <div class="row">
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="phone"><strong>Phone:</strong></label>
                                        <input type="text" class="form-control" name="phone"
                                               id="phone" placeholder="Phone" value="{{old('phone')}}"/>
                                    </div>
                                </div>

                                <div class="col-12 col-md-3">
                                    <div class="form-group">
                                        <label for="gender"><strong>Gender:</strong></label>
                                        <select class="form-control" name="gender" id="gender">
                                            <option selected>Male</option>
                                            <option>Female</option>
                                            <option>Other</option>
                                        </select>
                                    </div>
                                </div>

                            <div class="form-group">
                                <label for="photo"><strong>Profile Picture:</strong></label>
                                <input type="file" class="form-control-file" name="photo" id="photo" accept="image/*">
                            </div>

                            <div class="row">
                                 <div class=" col-12 text-center">
                                    <input type="submit" class="btn btn-primary pr-3 pl-3" value="Submit" id="submit"/>
                                </div>
                            </div>



                        </form>
                    </div>
                </div>

            </div>
            <div class="col-auto">
                <div class="text-danger">
                    @foreach($errors->all() as $err)
                        {{$err}} <br>
                    @endforeach
                    {{session('msg')}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/staff/index.blade.php
@extends('layouts.staff')
@section('content')
<div class="container" style="margin-top:30px">
    <div class="row">

        <div class="col-sm-4">
            <h2>STAFF: {{$user->s_id}}</h2>
            <img src="{{asset('img/'.$user->photo)}}" class="rounded mx-auto d-block img-thumbnail" style="width: auto;height: 200px">
            <div class="card-body text-center">
                <div class="h5 text-left">
                    <div class="row">
                        <div class="col-6 text-right">Name: </div>
                        <div class="col-6">{{$user->name}}</div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">Phone: </div>
                        <div class="col-6">{{$user->phone}}</div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">Gender: </div>
                        <div class="col-6">{{$user->gender}}</div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@endsection