routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');//->middleware('sess');
Route::resource('staff',\App\Http\Controllers\StaffController::class);
Route::resource('staff.userList',\App\Http\Controllers\StaffUserListController::class);
Route::resource('staff.doctorList',\App\Http\Controllers\StaffDoctorListController::class);
Route::get('userList/{userList}/delete/{id}',[App\Http\Controllers\StaffUserListController::class,'delete'])->name('userList.delete');
Route::resource('staff.forum',\App\Http\Controllers\StaffForumController::class);
Route::resource('staff.forum.comment',\App\Http\Controllers\StaffCommentController::class);
Route::resource('staff.feedback',\App\Http\Controllers\StaffFeedbackController::class);
Route::put('/staff/{staff}/doctorList/{doctorList}/ban/{id}',[App\Http\Controllers\StaffDoctorListController::class,'ban'])->name('doctorList.ban');

app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    use HasFactory;
    protected $primaryKey='s_id';
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StaffRequests;
use App\Models\admin;
use App\Models\Staff;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

//use Illuminate\Support\Facades\Auth;
//use Illuminate\Support\Facades\DB;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    /*$doctor=DB::table('staff')
            ->rightJoin('users','staff.s_id','=','users.id')
            ->where('userId','=',Auth::user()->id)
            ->get();
    print_r($staff);
    return view('staff.profile')->with('users',$users);*/
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {   $staff=DB::table('staff')
        ->join('users','staff.userId','=','users.id')
        ->where('userId','=',Auth::user()->id)
        ->get();
        //print_r($doctor);
        if(count($staff)) {

            return view('staff.index')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
        return view('staff.index')->with('user',$staff[0]);

    }
    /*public function profile(Request $request)
    {
        $staff=DB::table('staff')
            ->join('users','staff.userId','=','users.id')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)) {

            return view('staff.index')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
        return view('staff.profile')->with('user',$staff[0]);
    }*/
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)==0){
            $request->session()->flash('msg','Please Complete Your Profile');
            return view('staff.create');
        }
        else{
            return redirect()->route('staff.index');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StaffRequests $request)
    {
        $staff=new Staff();
        $staff->phone=$request->phone;
        $staff->gender=$request->gender;
        $staff->userId=Auth::user()->id;

        if($request->hasFile('photo')){
            $file=$request->file('photo');
        //  echo "File Name: ". $file->getClientOriginalName()."<br>";
        //  echo "File Extension: ". $file->getClientOriginalExtension()."<br>";
        //   echo "File Size: ". $file->getSize()."<br>";
        //  echo "File Mime Type: ". $file->getMimeType();
            $filename=$file->getClientOriginalName();

            if($file->move('img', $filename)){
                $staff->photo = $filename;
                $staff->save();
                return redirect()->route('staff.index');
            }
            else{
                return redirect()->route('staff.create');
            }
        }
        else{
            echo 'Profile photo is not selected';
        }

    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,Staff $staff)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)) {

            return view('staff.index')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$staff)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($staff)) {
            $staff=DB::table('staff')
                ->where('userId','=',Auth::user()->id)
                ->get();
            return view('staff.edit')->with('user', $staff[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('staff.create');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function update(StaffUpdateRequests $request, $staff)
    {
        $staff=DB::table('staff')
            ->where('userId','=',Auth::user()->id)
            ->get();
        $staff->phone=$request->phone;
        $staff->gender=$request->gender;

        if($request->hasFile('photo')){
            $file=$request->file('photo');
//            echo "File Name: ". $file->getClientOriginalName()."<br>";
//            echo "File Extension: ". $file->getClientOriginalExtension()."<br>";
//            echo "File Size: ". $file->getSize()."<br>";
//            echo "File Mime Type: ". $file->getMimeType();
            $filename=$file->getClientOriginalName();

            if($file->move('img', $filename)){
                $staff->photo=$filename;

            }

        }
        $staff->save();
        return redirect()->route('staff.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function destroy(Staff $staff)
    {
        //
    }
}

resources/views/staff/userList/delete.blade.php
@extends('layouts.staff')
@section('content')
<!DOCTYPE html>
<html>
<head>
	<title>Delete User</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
</head>
<body>
    <form method="post" action="{{route('staff.userList.destroy',[Auth::user()->id,$user->id])}}">
		@csrf
        @method('DELETE')
        <input type="hidden" name="id" value="{{$user->id}}">
        <div class="container">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>User TYpe</th>
                </tr>
                </thead>
                <tbody>

                <tr class="table-danger">
                    <td>{{$user['name']}}</td>
                    <td>{{$user['email']}}</td>
                    <td>{{$user['type']}}</td>

		<h3>Do you really want to delete this user?</h3>
		<input type="submit" name="submit" value="Confirm">

                    <a href="{{route('staff.userList.index',Auth::user()->id)}}">

                    <button type="button" class="btn btn-success"> Back </button></a>
	</form>
</body>
</html>
@endsection

resources/views/staff/userList/index.blade.php
@extends('layouts.staff')
@section('content')
    <div class="container-fluid mt-2 text-center">
        <div class="row">
            <div class="col-12 col-md-12 offset-md-0">
                <div class="card shadow-sm bg-dark">
                    <table class="table table-dark table-hover table-striped text-center">
                        <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Type</th>
                            <th colspan="2">Action</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users->all() as $user)
                        <tr>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->type}}</td>
                            <td colspan="2">
                                <a href="{{route('userList.delete', [$user->id,$user->id])}}">Delete</a></td>

                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
            <div class="col-auto">
            </div>
        </div>
@endsection